

POST http://localhost:3000/api/Overlays
Content-Type: application/json

{
  "ids": [
    "1e0507e0-1706-a834-1a22-976f88d83a3d_20fa76e3-7d0b-8bb9-cc4d-4304558da497",
    "00"
  ]
}

###

POST http://localhost:3000/mock
Content-Type: application/json

{
    "paginationInfo": {
      "size": "500",
      "from": "0"
    },
    "conditions": [
      [
        {
          "matchQueries": [
            {
              "field": "sensorName",
              "value": "FreezedFrame"
            }
          ]
        },
        {
          "matchQueries": [
            {
              "field": "sensorName",
              "value": "ImportedFrame"
            }
          ]
        },
        {
          "matchQueries": [
            {
              "field": "sensorName",
              "value": "SAR"
            }
          ]
        },
        {
          "matchQueries": [
            {
              "field": "sensorName",
              "value": "CNIR"
            }
          ]
        },
        {
          "matchQueries": [
            {
              "field": "sensorName",
              "value": "Reccelite"
            }
          ]
        },
        {
          "matchQueries": [
            {
              "field": "sensorName",
              "value": "RTM"
            }
          ]
        }
      ],
      [
        {
          "rangeQueries": [
            {
              "field": "photoTime",
              "from": "2018-04-22T08:49:19.63Z",
              "to": "2018-04-22T09:19:19.63Z"
            }
          ]
        }
      ],
      [
        {
          "geoQueries": [
            {
              "field": "footprint",
              "relation": "intersects",
              "refine": 0.0,
              "polygon": {
                "coordinates": [
                  [
                    [
                      35.008159591908111,
                      32.721189303550673
                    ],
                    [
                      34.9884912952619,
                      32.544174625207
                    ],
                    [
                      34.9425986030874,
                      32.445833137238289
                    ],
                    [
                      34.798364427681811,
                      31.672213431884451
                    ],
                    [
                      35.329408437129636,
                      32.144252574134256
                    ],
                    [
                      35.434306019242776,
                      32.622847815581963
                    ],
                    [
                      35.008159591908111,
                      32.721189303550673
                    ]
                  ]
                ],
                "type": "Polygon"
              }
            }
          ]
        }
      ]
    ]
  }